### ISSUE TITLE
Add documentation about what happens when hitting `C-g` while entering summary

### ISSUE THREAD

**Issue by Kaligule** [ryuslash/git-auto-commit-mode#13]
It seems to me that hitting `C-g` while entering the summary will
still safe the file but not commit the change. There is nothing wrong
with that and it might even be the desired behavior (since there might
be good reasons to safe, but not commit).

It would be great if this behavior could be documented in the docstring for `gac-ask-for-summary-p` so the user knows about it.

**Comment by ryuslash** [comment]
Good point, I can't think of a reason why I would _want_ this to be the way it works, but I don't know if I can fix it. I'll have a look soon to see if I can do anything about it. The problem is that I use `after-save-hook`, so by the time you're asked for a summary, the file is already saved.

**Comment by ryuslash** [comment]
What do you think of the comment I've added in the latest master to the README?

**Comment by Kaligule** [comment]
@ryuslash I like it a lot, thank you.
