### ISSUE TITLE
Catch empty commits before asking for summary 

### ISSUE THREAD

**Issue by Kaligule** [ryuslash/git-auto-commit-mode#14]
It would be nice not to be asked for a summary if I save a file without having changed it. At the moment I enter a summary, just to be informed that there is nothing to commit.

**Comment by ryuslash** [comment]
Hi!
Thanks for reporting this issue! Sorry for the extreme delay in getting back to you.

This does sound like something that might be annoying. I will try and fix this when I can find the time to look into it.

**Comment by ryuslash** [comment]
This should be fixed now in the latest master, please let me know if you run into any issues by either reopening this issue or creating a new one.
