### ISSUE TITLE
git exited abnormally with code 128

### ISSUE THREAD

**Issue by petergerten** [ryuslash/git-auto-commit-mode#15]
On every commit I get "git exited abnormally with code 128", though everything seems to work.
Any idea why I get that?

**Comment by ryuslash** [comment]
Hi!
I'm sorry for the extreme delay! I realize that you have most likely moved on or found a fix on your own, but still I wanted to make an attempt.

Do you have `gac-automatically-push-p` set? From a quick internet search it sounds like git might be having trouble connecting to a remote. This might happen if whatever settings you use to authenticate with the remote don't carry over into Emacs' process.

**Comment by ryuslash** [comment]
I'm guessing I took to long to respond to this and you're either not using git-auto-commit-mode any more or your issue has been fixed. Either way I'm closing this issue. Feel free to re-open it if you feel the need.
