### ISSUE TITLE
New files won't be committed 

### ISSUE THREAD

**Issue by mrvdb** [ryuslash/git-auto-commit-mode#20]
I've been using gac to automatically commit my journal files using a `.dir-locals.el`  file in the root of the folder tree where the journal files live.

```((org-mode . ((eval git-auto-commit-mode 1))))```

It seems that commit https://github.com/ryuslash/git-auto-commit-mode/commit/5bb26c63843381d9b3dad7708970a93494d20b26 changed the behaviour of the package a bit where files that are not in the index won't be added anymore.

Could this perhaps be made into an option?

The issue made me think of this : https://xkcd.com/1172/

![image](https://user-images.githubusercontent.com/73067/69318859-557d4480-0c3e-11ea-8e0b-32b108721bba.png)

**Comment by ryuslash** [comment]
Hey, thanks for the report. Woops! Yeah this wasn't intentional. I'll try and get it working the old way again (possibly as an option) as soon as I have some time to work on this again.

**Comment by ryuslash** [comment]
Ok, I've committed a fix for this on the master branch, please let me know if everything works correctly this way. I've added a (dumb) test to hopefully make sure that this doesn't happen again.

Please let me know if this fixes things for you.

**Comment by mrvdb** [comment]
Yup, good to go for me. Thanks!
