### ISSUE TITLE
Should untracked files be added?

### ISSUE THREAD

**Issue by ThibautVerron** [ryuslash/git-auto-commit-mode#21]
(Piggy-backing on issue https://github.com/ryuslash/git-auto-commit-mode/issues/20 )

Hello,

It looks like the expected behavior when saving untracked files is "always add and commit".

It would be nice to have an option to never add new files (i.e. only auto-commit already tracked files), or to ask the user when saving an untracked file for the first time. Since the other issue looks like it will require to do something specific for untracked files, it might be a good occasion to add this too?

**Comment by ryuslash** [comment]
Hey, thanks for the request! Yeah that sounds like a good idea, I'll try and do this as soon as I have some time to work on this again.

**Comment by ryuslash** [comment]
I've added a `gac-automatically-add-new-files-p` custom. I decided to go with just a variable, at least for now, because it was easier to test than asking the user for input. Please let me know if this works for you.

**Comment by ryuslash** [comment]
I will assume this was adequate as there has been no response. Please feel free to re-open this issue or create a new one if there is anything else :)
