### ISSUE TITLE
I don't understand how to enable this as "a directory-local variable"

### ISSUE THREAD

**Issue by mrbig033** [ryuslash/git-auto-commit-mode#22]
### My Environment

- **OS**: MX Linux 18
- **$ uname -r**: 4.19.0-5-amd64
- [dotfiles](https://github.com/mrbig033/dotfiles)
- **i3wm** version 4.13
- [~/.config/i3](https://github.com/mrbig033/dotfiles/blob/master/i3/config)
- **GNU Emacs** 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2019-11-19
- [~/.emacs.d](https://github.com/mrbig033/emacs02)
- git-auto-commit-mode Version: 20191008.429

### Issue

I've read the relevant read the [readme section](https://github.com/ryuslash/git-auto-commit-mode#as-a-directory-local-variable), but I don't understand how to actually apply it to my configuration. I mean, where do I put the directory? Or am I suppose to put this in a file within the directory?

``` emacs-lisp
((nil . ((eval git-auto-commit-mode 1))))
```

**Comment by ryuslash** [comment]
Hey! 

This goes in a file named `.dir-locals.el` in whichever directory you want it to apply to (this will also apply to any subdirectories). You can find more information in the [Directory Variables](https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html#Directory-Variables) section of the emacs manual. I'm sorry if this isn't very clear in the README, I'll expand the section to include this.

**Comment by mrbig033** [comment]
Okay, this works. Thanks for answering.
