### ISSUE TITLE
Feature request: commit message customization

### ISSUE THREAD

**Issue by saidie** [ryuslash/git-auto-commit-mode#23]
Hi,

I really love this package and am using heavily (hundreds of auto commits a day).
Now, I'm writing a script to squash some commits by hour to compact the git repository but it is difficult to distinguish which commit is by git-auto-commit. I think I can solve this if we have commit message customization.
So, it would be great if such customization is supported!

Thanks

---

Actually I have a workaround like:

```elisp
(advice-add 'gac--commit-msg
            :filter-return
            (lambda (msg) (concat "[gac] " msg)))
```

But this could be broken in the future :crying_cat_face:

**Comment by ryuslash** [comment]
Hey!

Glad to hear that it's been useful for you! Is there something that's preventing you from using the `gac-default-message` and / or `gac-ask-for-summary-p` options to either change the message for every commit or ask for the message each time it commits?

**Comment by saidie** [comment]
> gac-default-message

This is exactly what I need! I did not notice this because I'm using the package on MELPA Stable (which is 4.5.0). Thank you for your time!
