### ISSUE TITLE
Which shell does this use?

### ISSUE THREAD

**Issue by NightMachinary** [ryuslash/git-auto-commit-mode#27]
I don’t want it to use my default shell (because of heavy dotfiles), but to use `dash`.

**Comment by ryuslash** [comment]
`git-auto-commit-mode` uses `shell-command` and `shell-command-to-string` for most of its calls to git. It uses `start-process` for pushing. `shell-command(-to-string)` use whichever shell is specified in `shell-file-name`, which is usually your default shell. I don't thing `start-process` uses a shell at all.

There isn't a way right now to change the shell that git-auto-commit-uses without changing the shell that everything calling `shell-command(-to-string)` uses.

**Comment by ryuslash** [comment]
I this still something you need fixed? Or has the information I provided you given you what you needed?

**Comment by NightMachinary** [comment]
Thanks!
