### ISSUE TITLE
How can I make this silent?

### ISSUE THREAD

**Issue by mrbig033** [ryuslash/git-auto-commit-mode#28]
I wish for this mode to commit without emitting any message in the echo area. How can I do that?

**Comment by ryuslash** [comment]
Hey :)

Right now there isn't any easy way that I can think of, but I can add something for that.

**Comment by ryuslash** [comment]
Have you tried the latest version which includes #29 ? Does this work for you?

**Comment by ryuslash** [comment]
I will assume this is adequate as there has been no response to this issue. Please feel free to re-open or create a new issue if there are any more problems :)
