### ISSUE TITLE
Fails if "[" is in a parent-folder-name

### ISSUE THREAD

**Issue by veev5Aej** [ryuslash/git-auto-commit-mode#30]
I am using Emacs 26 with Linux and when I save the file this error message occur when a parent-folder contains `[`:

`replace-regexp-in-string: Invalid regexp: "Unmatched [ or [^"`

(And BTW the error doesn't occur when the file itself contains a `[`.)

**Comment by ryuslash** [comment]
Hi,

Thanks for letting me know!

 I've pushed a change that according to my local tests should fix the problem, can you give it a try please?

**Comment by veev5Aej** [comment]
Yes, it works now.
Thanks!
