### ISSUE TITLE
Auto Push does not work

### ISSUE THREAD

**Issue by systemhalted** [ryuslash/git-auto-commit-mode#33]
First of all, thank you for creating this minor mode. 

My .dir-locals-el file has following config

``` emacs-lisp
((nil . ((eval git-auto-commit-mode 1))))
(setq-default gac-automatically-push-p t)
(setq-default gac-debounce-interval 60)
```
However, I have two issues
1. All files are not activated with the GAC mode
2. The push does not happen automatically.

Can you help me? I am not sure if I am using it correctly.

**Comment by ryuslash** [comment]
Hey 🙂 thanks for opening an issue. The `.dir-locals.el` is not a file that gets evaluated as a regular Emacs lisp file. I think it just takes the first list and runs it through some local variables functions, so the `setq-default` calls won't actually do anything.

If you want to set things up this way you probably want to use something like:
```
((nil . ((eval git-auto-commit-mode 1)
         (gac-automatically-push-p . t)
         (gac-debounce-interval . 60))))
```
Which will set the values of the variables in every buffer for each file opened in your directory and any subdirectories. You can inspect it out worked right by calling `describe-variable` and they will show the value you specified if it worked correctly.

**Comment by systemhalted** [comment]
It works. Thank you. Closing this issue!
