### ISSUE TITLE
documentation unclear

### ISSUE THREAD

**Issue by singingfish** [ryuslash/git-auto-commit-mode#35]
Thanks for this.  I just implemented my dream org-mode workflow :)

I tried putting the following in `.dir_locals.el` but it didn't work. 

```
(setq-default gac-ask-for-summary-p t)
(setq-default gac-automatically-push-p t)

```

 It's probably worth making note in the docs that this should go in `.emacs` or perhaps indicating what syntax should be used if going in `.dir_locals.el`

**Comment by ryuslash** [comment]
Hey :)

Glad to hear it's useful to you!

Thanks for the suggestion. I've added a note about how to configure the variables in the latest commit, what do you think?

**Comment by singingfish** [comment]
great, thanks :)
