### ISSUE TITLE
any way to specify a string prefix for the automatic commit message

### ISSUE THREAD

**Issue by la-ruby** [ryuslash/git-auto-commit-mode#43]
Is it possible (or would you accept a PR) for end user to specify a prefix for the auto commit message.

Before

```
commit 4b036f7b4eed265d8d7f2266a26589e5d279ac4a (HEAD -> nov-updates)
Author: Anon <a@example.com>
Date:   Mon Dec 5 19:08:43 2022 -0800

    example/notes.txt
```

After

(setq gac-my-prefix "wip")

```
commit 4b036f7b4eed265d8d7f2266a26589e5d279ac4a (HEAD -> nov-updates)
Author: Anon <a@example.com>
Date:   Mon Dec 5 19:08:43 2022 -0800

    wip example/notes.txt
```

**Comment by ryuslash** [comment]
Hey!

I haven't tried this myself, but yes it should be possible by setting `gac-default-message` to a function:

```elisp
(defun my-commit-message (filename)
  "Specify that my commit is a work in progress"
  (concat "wip " (gac-relative-name filename)))

(with-eval-after-load 'git-auto-commit-mode
  (setq gac-default-message #'my-commit-message))
```

Although looking at the code I think there might be a bug in there, so please try it, but also I will have a look at it.

**Comment by la-ruby** [comment]
This function `gac-relative-name`, wondering where that should reside.

<img width="834" alt="CleanShot 2022-12-07 at 15 16 29@2x" src="https://user-images.githubusercontent.com/55279023/206317841-3abef5c6-0d29-4ac1-b6e2-a538c384773d.png">

**Comment by ryuslash** [comment]
Woops! Sorry, that should be `gac-relative-file-name` and it lives in `git-auto-commit-mode.el`

**Comment by la-ruby** [comment]
now this is legit! 

great to see a maintainer who's active and cares ❤️
