### ISSUE TITLE
What to do to install git-auto-commit-mode?

### ISSUE THREAD

**Issue by kunass2** [ryuslash/git-auto-commit-mode#7]
I try to make it working. So far I installed Emacs 24. I know about this, because when I check 
`emacs --version` in my directory using my console, then I get `24.5.1`

I also created `.dir-locals.el` file with content:
     `((nil . ((eval git-auto-commit-mode 1))))`

Then I added that file to my local git repository, as it is on the image below:
![screen shot 2015-05-09 at 12 21 35](https://cloud.githubusercontent.com/assets/9480650/7549786/08d112f0-f646-11e4-85c3-0bc0c8e6fcbb.png)

Then i changed some files inside my git-repo and saved changes. But nothing happened automatically. So what should i do more to accomplish my task?

**Comment by ryuslash** [comment]
From what you tell me you should have done everything you need to. To test this I've made a new directory somewhere (`~/tmp/gactest`), made it a git repository (with `git init`), added a `dir-locals.el` file with those same contents, added a file with a little content, then opened that file in Emacs, changed it and saved it and it got committed.

So I have to ask a few questions:

- Which version of git-auto-commit-mode do you have installed?
- Do you use `package.el` or something like Cask or something else to install your packages?
- Do you get any messages, warnings or errors when you open a file which is supposed to have `git-auto-commit-mode` enabled?
- Were the files you changed already open in Emacs before you added the `.dir-locals.el` file, or did you open them after you put it in your repository?
- Is the `git` executable in your executable path (`$PATH`)?

I also feel I should tell you that from the look of your screenshot this is not the kind of thing that git-auto-commit-mode is really meant for. It's just meant for files or groups of files where the history itself is the only important part, not the description of the history, and where changes to a single file stand completely seperate from changes in other files. For example I use this to keep a history of my `tasks` file, which is an org-mode file containing my ever-growing todo list.

**Comment by kunass2** [comment]
1. Do you know how to check whether git-auto-commit-mode is installed or
not? And if not... what should I do to install this? This is my first time
with Emacs so I am in trouble.

The rest of your questions are strongly connected with the first, So I
first make sure that I installed it.

**Comment by ryuslash** [comment]
You can see if it's installed by trying `M-x git-auto-commit-mode` in a file where you want it enabled or a test file. If it gets enabled (you see `ga` added to your mode-line) it's installed, if you get a message that `git-auto-commit-mode` is not a valid command, it's not installed.

Installation instructions are: https://github.com/ryuslash/git-auto-commit-mode/blob/master/INSTALL

Please let me know if they don't make sense to you.

**Comment by kunass2** [comment]
I am trying to install it manually:

1. Downloaded files from (ryuslash/git-auto-commit-mode)[https://github.com/ryuslash/git-auto-commit-mode].
2. Added `git-auto-commit-mode-master` to my git directory.
3. Create a test file: `test.php` along with `.git` (image below). Then I add content of that file: `M-x git-auto-commit-mode`.

![screen shot 2015-05-18 at 20 20 39](https://cloud.githubusercontent.com/assets/9480650/7687146/6c392146-fd9b-11e4-8ce3-26b4082e02f9.png)


Everything is ok so far? What is next? I do not understand `load-path`...

**Comment by ryuslash** [comment]
It would probably be easiest to install it using MELPA or Marmalade.

From what I see you have done I'm going to suggest you might want to read the Emacs tutorial (in Emacs, pressing `CTRL+h` and then `t` should get you there, although on a mac it might be `Command+h` and then `t`).

There is no need to add `git-auto-commit-mode-master` to your project directory, you put it somewhere near your Emacs configuration file(s) and then add the directory the files are placed in to your `load-path` configuration variable as shown in the `INSTALL` file. This code is put in your `~/.emacs.d/init.el` file (or `~/.emacs` if that already exists). Once the directory containing `git-auto-commit-mode.el` is added to your load path, you can add `(require 'git-auto-commit-mode)` *or* `(autoload 'git-auto-commit-mode "git-auto-commit-mode")` (not both) to your `~/.emacs.d/init.el` file.

After you have done that and you have either evaluated the bits of code in your `~/.emacs.d/init.el` file or restarted Emacs, you should be able to use one of the methods described in the `README` to enable git-auto-commit-mode in the file(s) you want.
