### ISSUE TITLE
No commits are made on save

### ISSUE THREAD

**Issue by itsok-dontworry** [ryuslash/git-auto-commit-mode#8]
I've probably missed something but I don't get automatic commits on save. I have installed the package (MELPA), created the `.dir-local.el` file and another test file `test.txt`. I've initialised git and did also an initial commit for that one file. When I open `test.txt` in emacs I get prompted for whether I want to set the directory variable, I say yes and `git-auto-commit-mode` is set to `t`. I make some changes to the file, save it. No new commits in the log.

Can you tell me what I have missed?

**Comment by ryuslash** [comment]
Hi,

Sorry for the slow response. You shouldn't be prompted to allow the variable to be set. Local variables in the form of `(eval some-minor-mode 1)` should always be allowed in file and directory-local settings.

Which version of Emacs are you using? And what exactly did you put in the `.dir-locals.el` file?

When I follow your example and have the following contents in my `.dir-locals.el` everything works fine and I am not prompted to allow the variable to be set:

```elisp
((nil . ((eval git-auto-commit-mode 1))))
```

This should work for Emacs 24 and up.

**Comment by itsok-dontworry** [comment]
Yes you are right. I must have a conflict in my `init.el`. I've tried it again with a clean config file and it works like a charm and I'm also not being prompted to allow the variable to be set. Sorry, I should've tried a clean config before posting an issue. Thank you!
